version: '3'

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  mysql8:
    driver: local


services:

  #MySQL Service
  mysql:
    image: mysql:latest
    restart: unless-stopped
    tty: true
    ports:
      - "33066:3306"
    environment:
      MYSQL_DATABASE: ojowo
      MYSQL_USER: DOCK
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql8:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

